### ISSUE TITLE
Integration / system-level testing

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/lms-2024#214]
Would be nice to have testing that covers app execution, especially for CLI stuff.

When working on #81 , it is unfeasible to test manually because I don't have the DB set up.

# Tasks
- [ ] Determine method of automating the CLI interaction. Options I know of include `expect` or `pexpect`. There are also options like [cli-testing-library](https://github.com/crutchcorn/cli-testing-library). We should **research** available options and pick one that looks best.
- [ ] Write tests to cover existing functionality
- [ ] Update CI/CD to run tests on pull requests.

# Other notes
- Since we have a `sqllite` db, we should ensure this DB is properly removed between tests.
