### ISSUE TITLE
Documentation work from Meeting 1

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/lms-2024#245]
# Overview
1. Folks requested some additional documentation for our operations-type tasks. Things like setting up integration/system testing
2. We should also spend time making sure our general documentation includes pointers. There are a ton of documentation sources on the internet, but not all are good

# Tasks
- [x] Determine instructional material needed for operations tasks
- [ ] Add instructional material to wiki
- [ ] Link wiki material to tasks

# Areas
- Linux
- CI/CD
- Software projects
