### ISSUE TITLE
report test coverage

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/lms-2024#93]
#22  gives us a basic test project and pipeline. I would like to expand on this by calculating a code coverage metric from these tests. This will give us a sense of what parts of the code have not been tested.

# Tasks
- [x] Determine how our test project (`xUnit`) can output test coverage
- [x] Determine how GitHub Actions can find and report test coverage
- [x] Update GitHub Action to report test coverage
